[pytest]
pythonpath = .
testpaths = tests
addopts = -q
filterwarnings =
    ignore::DeprecationWarning
    ignore::starlette.middleware.exceptions.StarletteDeprecationWarning
    ignore:Using `httpx` with `starlette.testclient`:starlette.middleware.exceptions.StarletteDeprecationWarning
    ignore:Using `httpx` with `starlette.testclient`:DeprecationWarning
